obj-m         := sstf.o
BUILDROOT_DIR := $(CURDIR)/../..
KDIR          := $(BUILDROOT_DIR)/output/build/linux-6.12.27
COMPILER      := $(BUILDROOT_DIR)/output/host/bin/i686-buildroot-linux-gnu-gcc

# Acesso ao header interno block/elevator.h (não estável para módulos out-of-tree)
ccflags-y := -I$(src)/../../output/build/linux-6.12.27/block

all: install

install: build
	$(MAKE) -C $(KDIR) M=$$PWD modules_install INSTALL_MOD_PATH=$(BUILDROOT_DIR)/output/target

build:
	$(MAKE) CC=$(COMPILER) -C $(KDIR) M=$$PWD modules

clean:
	$(MAKE) -C $(KDIR) M=$$PWD clean
